name: Issue Labeled Workflow

on:
  issues:
    types:
      - labeled
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run similarity when labeled
        if: github.event_name == 'labeled'
        uses: actions-cool/issues-similarity-analysis@main
        with:
          filter-threshold: 0.5
          title-excludes: "bug, not, 1234"
          comment-title: "### Similar issues"
          comment-body: "${index}. ${similarity} #${number}"
