name: Issue Labeled Workflow

on:
  issues:
    types:
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run when labeled
        if: contains(github.event.issue.labels.*.name, 'specific-label')
        run: |
          echo "This workflow runs when the issue is labeled with 'specific-label'"
